### ISSUE TITLE
Morning Session: Peer to Peer Coding Review.

### ISSUE THREAD

**Issue by Recillah-Khamala** [aamirkhan2478/awsome-books-es6#3]
### **Morning Session: Peer to Peer Coding Review.**

**Good job** working on this project so far. 💪 👏 👏 .

- The project looks promising.
- Good job on the design. This makes the project truly yours. 
- Good use of modules(You created many module files).

Optional changes.

Kindly consider making the below suggestions.

- The current font makes your design look scattered, would you consider using a different font?
- Adding a Live demo to your README. md file makes your work readily presentable, how about you add this?
- How about making some improvements in the DRY approach? You can avoid the repetition of code in addbooks for input validation (title and author are empty).
- We also recommend the use of Date.now() (or any luxon equivalent) in the generation of unique ids instead of Math.random(). This will reduce the chances of any id collisions in your project making it more robust.

**Comment by aamirkhan2478** [comment]
✔️ The current font makes your design look scattered, would you consider using a different font?
✔️ Adding a Live demo to your README. md file makes your work readily presentable, how about you add this?
✔️ How about making some improvements in the DRY approach? You can avoid the repetition of code in addbooks for input validation (title and author are empty).
✔️ We also recommend the use of Date.now() (or any luxon equivalent) in the generation of unique ids instead of Math.random(). This will reduce the chances of any id collisions in your project making it more robust.
